import { DEVICE_META, type CableKind, type CatalogCategory, type CatalogItem, type DeviceKind } from "./types";

function item(
  id: string,
  brand: string,
  model: string,
  category: CatalogCategory,
  kind: DeviceKind | undefined,
  short: string,
  spec?: string,
  cable?: CatalogItem["cable"],
): CatalogItem {
  return { id, brand, model, category, kind, short, spec, cable };
}

/** Built-in AV library — install kit across the brands shops actually spec. */
export const STOCK_CATALOG: CatalogItem[] = [
  // Mixers
  item("yamaha-ql5", "Yamaha", "QL5", "mixer", "mixer", "QL5", "32 + 16 Dante"),
  item("yamaha-ql1", "Yamaha", "QL1", "mixer", "mixer", "QL1", "16 + 8 Dante"),
  item("yamaha-cl5", "Yamaha", "CL5", "mixer", "mixer", "CL5", "72 mix"),
  item("yamaha-cl3", "Yamaha", "CL3", "mixer", "mixer", "CL3", "64 mix"),
  item("yamaha-cl1", "Yamaha", "CL1", "mixer", "mixer", "CL1", "48 mix"),
  item("yamaha-dm7", "Yamaha", "DM7", "mixer", "mixer", "DM7", "120 ch"),
  item("yamaha-dm3", "Yamaha", "DM3", "mixer", "mixer", "DM3", "22 ch Dante"),
  item("yamaha-tf5", "Yamaha", "TF5", "mixer", "mixer", "TF5", "32 ch"),
  item("yamaha-tf3", "Yamaha", "TF3", "mixer", "mixer", "TF3", "24 ch"),
  item("yamaha-tf1", "Yamaha", "TF1", "mixer", "mixer", "TF1", "16 ch"),
  item("yamaha-pm5", "Yamaha", "Rivage PM5", "mixer", "mixer", "PM5", "144 mix"),
  item("yamaha-pm7", "Yamaha", "Rivage PM7", "mixer", "mixer", "PM7", "120 mix"),
  item("yamaha-mg32", "Yamaha", "MG32XU", "mixer", "mixer", "MG32", "32 ch analog"),
  item("yamaha-mg16", "Yamaha", "MG16XU", "mixer", "mixer", "MG16", "16 ch analog"),
  item("yamaha-mgp32", "Yamaha", "MGP32X", "mixer", "mixer", "MGP", "32 ch analog"),
  item("ah-sq5", "Allen & Heath", "SQ-5", "mixer", "mixer", "SQ5", "48 ch 96 kHz"),
  item("ah-sq6", "Allen & Heath", "SQ-6", "mixer", "mixer", "SQ6", "48 ch"),
  item("ah-sq7", "Allen & Heath", "SQ-7", "mixer", "mixer", "SQ7", "48 ch"),
  item("ah-avantis", "Allen & Heath", "Avantis", "mixer", "mixer", "AVA", "64 ch"),
  item("ah-avantis-solo", "Allen & Heath", "Avantis Solo", "mixer", "mixer", "AVAS", "64 ch compact"),
  item("ah-s3000", "Allen & Heath", "dLive S3000", "mixer", "mixer", "S3K", "128 ch"),
  item("ah-s5000", "Allen & Heath", "dLive S5000", "mixer", "mixer", "S5K", "128 ch"),
  item("ah-s7000", "Allen & Heath", "dLive S7000", "mixer", "mixer", "S7K", "128 ch"),
  item("ah-cq18", "Allen & Heath", "CQ-18T", "mixer", "mixer", "CQ18", "18 ch compact"),
  item("ah-cq20", "Allen & Heath", "CQ-20B", "mixer", "mixer", "CQ20", "20 ch rack"),
  item("ah-qu16", "Allen & Heath", "QU-16", "mixer", "mixer", "QU16", "16 ch"),
  item("ah-qu24", "Allen & Heath", "QU-24", "mixer", "mixer", "QU24", "24 ch"),
  item("ah-qu32", "Allen & Heath", "QU-32", "mixer", "mixer", "QU32", "32 ch"),
  item("behr-wing", "Behringer", "Wing", "mixer", "mixer", "WING", "48 stereo / 8 dual"),
  item("behr-wingc", "Behringer", "Wing Compact", "mixer", "mixer", "WINGC", "48 ch digital"),
  item("behr-wingr", "Behringer", "Wing Rack", "mixer", "mixer", "WINGR", "48 ch rack"),
  item("behr-x32", "Behringer", "X32", "mixer", "mixer", "X32", "32 ch digital"),
  item("behr-x32c", "Behringer", "X32 Compact", "mixer", "mixer", "X32C", "32 ch compact"),
  item("behr-x32p", "Behringer", "X32 Producer", "mixer", "mixer", "X32P", "32 ch producer"),
  item("behr-x32r", "Behringer", "X32 Rack", "mixer", "mixer", "X32R", "32 ch rack"),
  item("behr-x32core", "Behringer", "X32 Core", "mixer", "mixer", "X32K", "40-in engine"),
  item("behr-xr18", "Behringer", "XR18", "mixer", "mixer", "XR18", "18 ch rack"),
  item("behr-xr16", "Behringer", "XR16", "mixer", "mixer", "XR16", "16 ch rack"),
  item("midas-m32", "Midas", "M32", "mixer", "mixer", "M32", "32 ch"),
  item("midas-m32r", "Midas", "M32R LIVE", "mixer", "mixer", "M32R", "32 ch compact"),
  item("midas-m32c", "Midas", "M32C", "mixer", "mixer", "M32C", "32 ch rack"),
  item("midas-hd96", "Midas", "Heritage-D HD96-24", "mixer", "mixer", "HD96", "144 in"),
  item("soundcraft-si1", "Soundcraft", "Si Expression 1", "mixer", "mixer", "SI1", "16 ch"),
  item("soundcraft-si2", "Soundcraft", "Si Expression 2", "mixer", "mixer", "SI2", "24 ch"),
  item("soundcraft-si3", "Soundcraft", "Si Expression 3", "mixer", "mixer", "SI3", "32 ch"),
  item("soundcraft-impact", "Soundcraft", "Si Impact", "mixer", "mixer", "IMP", "32 ch"),
  item("soundcraft-ui24", "Soundcraft", "Ui24R", "mixer", "mixer", "UI24", "24 ch rack"),
  item("soundcraft-ui16", "Soundcraft", "Ui16", "mixer", "mixer", "UI16", "16 ch rack"),
  item("soundcraft-sig22", "Soundcraft", "Signature 22 MTK", "mixer", "mixer", "SIG", "22 ch analog"),
  item("presonus-32sc", "PreSonus", "StudioLive 32SC", "mixer", "mixer", "SL32", "32 ch"),
  item("presonus-32sx", "PreSonus", "StudioLive 32SX", "mixer", "mixer", "SL32X", "32 ch"),
  item("presonus-64s", "PreSonus", "StudioLive 64S", "mixer", "mixer", "SL64", "64 ch"),
  item("presonus-32r", "PreSonus", "StudioLive 32R", "mixer", "mixer", "SL32R", "32 ch rack"),
  item("presonus-16r", "PreSonus", "StudioLive 16R", "mixer", "mixer", "SL16R", "16 ch rack"),
  item("digico-sd12", "DiGiCo", "SD12", "mixer", "mixer", "SD12", "72 ch"),
  item("digico-sd9", "DiGiCo", "SD9", "mixer", "mixer", "SD9", "96 ch"),
  item("digico-sd10", "DiGiCo", "SD10", "mixer", "mixer", "SD10", "96 ch"),
  item("digico-q225", "DiGiCo", "Quantum 225", "mixer", "mixer", "Q225", "72 ch"),
  item("digico-q338", "DiGiCo", "Quantum 338", "mixer", "mixer", "Q338", "128 ch"),
  item("ssl-l100", "SSL", "Live L100", "mixer", "mixer", "L100", "144 in"),
  item("ssl-l200", "SSL", "Live L200", "mixer", "mixer", "L200", "192 in"),
  item("ssl-l550", "SSL", "Live L550", "mixer", "mixer", "L550", "256 in"),
  item("avid-s6l24", "Avid", "S6L-24D", "mixer", "mixer", "S6L", "Venue"),
  item("avid-s6l32", "Avid", "S6L-32D", "mixer", "mixer", "S6L32", "Venue"),
  item("mackie-dl32r", "Mackie", "DL32R", "mixer", "mixer", "DL32", "32 ch rack"),
  item("mackie-profx12", "Mackie", "ProFX12v3+", "mixer", "mixer", "PFX", "12 ch analog"),
  item("mackie-vlz16", "Mackie", "1604VLZ4", "mixer", "mixer", "VLZ", "16 ch analog"),
  item("roland-m5000", "Roland", "M-5000", "mixer", "mixer", "M5K", "128 ch"),
  item("roland-vr120", "Roland", "VR-120HD", "mixer", "mixer", "VR120", "AV mixer"),
  item("qsc-tm8", "QSC", "TouchMix-8", "mixer", "mixer", "TM8", "8 ch"),
  item("qsc-tm16", "QSC", "TouchMix-16", "mixer", "mixer", "TM16", "16 ch"),
  item("qsc-tm30", "QSC", "TouchMix-30 Pro", "mixer", "mixer", "TM30", "32 ch"),

  // Stage boxes
  item("yamaha-tio", "Yamaha", "Tio1608-D", "stagebox", "stagebox", "TIO", "16 in / 8 out Dante"),
  item("yamaha-rio16", "Yamaha", "Rio1608-D2", "stagebox", "stagebox", "RIO16", "16 in / 8 out Dante"),
  item("yamaha-rio32", "Yamaha", "Rio3224-D2", "stagebox", "stagebox", "RIO", "32 in / 24 out Dante"),
  item("ah-dx168", "Allen & Heath", "DX168", "stagebox", "stagebox", "DX", "16 in / 8 out"),
  item("ah-dx164", "Allen & Heath", "DX164-W", "stagebox", "stagebox", "DXW", "16 in wall"),
  item("ah-ab168", "Allen & Heath", "AB168", "stagebox", "stagebox", "AB", "16 in / 8 out"),
  item("ah-gx4816", "Allen & Heath", "GX4816", "stagebox", "stagebox", "GX", "48 in / 16 out"),
  item("ah-dt168", "Allen & Heath", "DT168", "stagebox", "stagebox", "DT", "16 in Dante"),
  item("behr-sd8", "Behringer", "SD8", "stagebox", "stagebox", "SD8", "8 in / 8 out AES50"),
  item("behr-sd16", "Behringer", "SD16", "stagebox", "stagebox", "SD16", "16 in / 8 out AES50"),
  item("behr-s16", "Behringer", "S16", "stagebox", "stagebox", "S16", "16 in / 8 out"),
  item("behr-s32", "Behringer", "S32", "stagebox", "stagebox", "S32", "32 in / 16 out"),
  item("behr-dl16", "Behringer", "DL16", "stagebox", "stagebox", "DL16", "16 in digital snake"),
  item("midas-dl8", "Midas", "DL8", "stagebox", "stagebox", "DL8", "8 in / 8 out"),
  item("midas-dl16", "Midas", "DL16", "stagebox", "stagebox", "DL16M", "16 in / 8 out"),
  item("midas-dl32", "Midas", "DL32", "stagebox", "stagebox", "DL32", "32 in / 16 out"),
  item("midas-dl151", "Midas", "DL151", "stagebox", "stagebox", "DL151", "24 in"),
  item("digico-sdrack", "DiGiCo", "SD-Rack", "stagebox", "stagebox", "SDR", "56 in / 56 out"),
  item("digico-d2rack", "DiGiCo", "D2-Rack", "stagebox", "stagebox", "D2R", "48 in / 16 out"),
  item("ssl-ml32", "SSL", "ML 32.32", "stagebox", "stagebox", "ML32", "32 in / 32 out"),

  // Amplifiers
  item("qsc-gx3", "QSC", "GX3", "amplifier", "amp", "GX3", "2 × 300 W"),
  item("qsc-gx5", "QSC", "GX5", "amplifier", "amp", "GX5", "2 × 500 W"),
  item("qsc-gx7", "QSC", "GX7", "amplifier", "amp", "GX7", "2 × 725 W"),
  item("qsc-pld42", "QSC", "PLD4.2", "amplifier", "amp", "PLD", "4 ch processing"),
  item("qsc-pld43", "QSC", "PLD4.3", "amplifier", "amp", "PLD3", "4 ch"),
  item("qsc-cxq4k4", "QSC", "CX-Q 4K4", "amplifier", "amp", "CXQ", "4 ch Q-SYS"),
  item("qsc-cxd42", "QSC", "CXD4.2", "amplifier", "amp", "CXD", "4 ch install"),
  item("qsc-dca1622", "QSC", "DCA 1622", "amplifier", "amp", "DCA", "2 × 800 W"),
  item("crown-xls1502", "Crown", "XLS 1502", "amplifier", "amp", "XLS", "2 × 525 W"),
  item("crown-xls2002", "Crown", "XLS 2002", "amplifier", "amp", "XLS2", "2 × 650 W"),
  item("crown-xls2502", "Crown", "XLS 2502", "amplifier", "amp", "XLS25", "2 × 775 W"),
  item("crown-xti4002", "Crown", "XTi 4002", "amplifier", "amp", "XTI", "2 × 1200 W"),
  item("crown-cdi4300", "Crown", "CDi 4|300", "amplifier", "amp", "CDI", "4 × 300 W"),
  item("crown-cdi4600", "Crown", "CDi 4|600", "amplifier", "amp", "CDI6", "4 × 600 W"),
  item("crown-dci2300", "Crown", "DCi 2|300", "amplifier", "amp", "DCI", "2 × 300 W 70 V"),
  item("crown-dci41250", "Crown", "DCi 4|1250", "amplifier", "amp", "DCI4", "4 × 1250 W"),
  item("crown-itech4", "Crown", "I-Tech 4x3500HD", "amplifier", "amp", "IT4", "4 ch tour"),
  item("powersoft-t604", "Powersoft", "T604", "amplifier", "amp", "T604", "4 ch install"),
  item("powersoft-t904", "Powersoft", "T904", "amplifier", "amp", "T904", "4 ch"),
  item("powersoft-x4", "Powersoft", "X4", "amplifier", "amp", "X4", "4 ch tour"),
  item("powersoft-x8", "Powersoft", "X8", "amplifier", "amp", "X8", "8 ch"),
  item("powersoft-otto", "Powersoft", "Ottocanali 4K4", "amplifier", "amp", "OTTO", "8 ch install"),
  item("powersoft-due", "Powersoft", "Duecanali 1604", "amplifier", "amp", "DUE", "2 ch install"),
  item("powersoft-mezzo", "Powersoft", "Mezzo 604 A", "amplifier", "amp", "MEZ", "4 × 150 W"),
  item("lab-fp10000", "Lab Gruppen", "FP 10000Q", "amplifier", "amp", "FPQ", "4 ch tour"),
  item("lab-plm12", "Lab Gruppen", "PLM 12K44", "amplifier", "amp", "PLM", "4 ch Lake"),
  item("lab-c104x", "Lab Gruppen", "C 10:4X", "amplifier", "amp", "C104", "4 ch install"),
  item("lab-d804", "Lab Gruppen", "D 80:4L", "amplifier", "amp", "D80", "4 ch"),
  item("lab-ipx", "Lab Gruppen", "IPX 2400", "amplifier", "amp", "IPX", "2 × 800 W"),
  item("yamaha-px3", "Yamaha", "PX3", "amplifier", "amp", "PX3", "2 × 300 W"),
  item("yamaha-px5", "Yamaha", "PX5", "amplifier", "amp", "PX5", "2 × 500 W"),
  item("yamaha-px8", "Yamaha", "PX8", "amplifier", "amp", "PX8", "2 × 800 W"),
  item("yamaha-px10", "Yamaha", "PX10", "amplifier", "amp", "PX10", "2 × 1000 W"),
  item("yamaha-pc412", "Yamaha", "PC412-D", "amplifier", "amp", "PC4", "4 ch Dante"),
  item("db-d20", "d&b audiotechnik", "D20", "amplifier", "amp", "D20", "4 ch tour"),
  item("db-d80", "d&b audiotechnik", "D80", "amplifier", "amp", "D80", "4 ch tour"),
  item("db-10d", "d&b audiotechnik", "10D", "amplifier", "amp", "10D", "4 ch install"),
  item("db-30d", "d&b audiotechnik", "30D", "amplifier", "amp", "30D", "4 ch install"),
  item("db-40d", "d&b audiotechnik", "40D", "amplifier", "amp", "40D", "4 ch install"),
  item("la-la4x", "L-Acoustics", "LA4X", "amplifier", "amp", "LA4X", "4 ch"),
  item("la-la12x", "L-Acoustics", "LA12X", "amplifier", "amp", "LA12", "4 ch"),
  item("la-la2xi", "L-Acoustics", "LA2Xi", "amplifier", "amp", "LA2X", "4 ch install"),
  item("bose-ps404", "Bose", "PowerShare PS404D", "amplifier", "amp", "PS4", "4 × 100 W"),
  item("bose-psa24", "Bose", "PSA2404", "amplifier", "amp", "PSA", "4 ch"),
  item("behr-nx3000", "Behringer", "NX3000", "amplifier", "amp", "NX3", "2 × 1500 W"),
  item("behr-nx6000", "Behringer", "NX6000", "amplifier", "amp", "NX6", "2 × 3000 W"),
  item("ev-q99", "Electro-Voice", "Q99", "amplifier", "amp", "Q99", "2 × 900 W"),
  item("ev-q1212", "Electro-Voice", "Q1212", "amplifier", "amp", "Q12", "2 × 1200 W"),

  // Speakers
  item("qsc-k8", "QSC", "K.8", "speaker", "speaker", "K8", "8 in active"),
  item("qsc-k10", "QSC", "K.10", "speaker", "speaker", "K10", "10 in active"),
  item("qsc-k12", "QSC", "K.12", "speaker", "speaker", "K12", "12 in active"),
  item("qsc-k82", "QSC", "K8.2", "speaker", "speaker", "K82", "8 in active"),
  item("qsc-k102", "QSC", "K10.2", "speaker", "speaker", "K102", "10 in active"),
  item("qsc-k122", "QSC", "K12.2", "speaker", "speaker", "K122", "12 in active"),
  item("qsc-ksub", "QSC", "KS118", "speaker", "speaker", "KSUB", "18 in sub"),
  item("qsc-ads8", "QSC", "AD-S8T", "speaker", "speaker", "ADS8", "8 in install"),
  item("qsc-ads6", "QSC", "AD-S6T", "speaker", "speaker", "ADS6", "6.5 in install"),
  item("qsc-ads4", "QSC", "AD-S4T", "speaker", "speaker", "ADS4", "4.5 in install"),
  item("qsc-cp8", "QSC", "CP8", "speaker", "speaker", "CP8", "8 in compact"),
  item("qsc-cp12", "QSC", "CP12", "speaker", "speaker", "CP12", "12 in compact"),
  item("yamaha-dzr10", "Yamaha", "DZR10", "speaker", "speaker", "DZR", "10 in active"),
  item("yamaha-dzr12", "Yamaha", "DZR12", "speaker", "speaker", "DZR12", "12 in active"),
  item("yamaha-dzr15", "Yamaha", "DZR15", "speaker", "speaker", "DZR15", "15 in active"),
  item("yamaha-dxr8", "Yamaha", "DXR8mkII", "speaker", "speaker", "DXR8", "8 in active"),
  item("yamaha-dxr12", "Yamaha", "DXR12mkII", "speaker", "speaker", "DXR", "12 in active"),
  item("yamaha-vxs8", "Yamaha", "VXS8", "speaker", "speaker", "VXS8", "8 in install"),
  item("yamaha-vxs5", "Yamaha", "VXS5", "speaker", "speaker", "VXS5", "5.5 in install"),
  item("yamaha-cbr12", "Yamaha", "CBR12", "speaker", "speaker", "CBR", "12 in passive"),
  item("ev-ekx12", "Electro-Voice", "EKX-12P", "speaker", "speaker", "EKX12", "12 in active"),
  item("ev-ekx15", "Electro-Voice", "EKX-15P", "speaker", "speaker", "EKX", "15 in active"),
  item("ev-elx", "Electro-Voice", "ELX200-12P", "speaker", "speaker", "ELX", "12 in active"),
  item("ev-evid", "Electro-Voice", "EVID-S5.2", "speaker", "speaker", "EVID", "5 in install"),
  item("ev-zlx", "Electro-Voice", "ZLX-12P", "speaker", "speaker", "ZLX", "12 in active"),
  item("ev-etx", "Electro-Voice", "ETX-12P", "speaker", "speaker", "ETX", "12 in active"),
  item("jbl-eon712", "JBL", "EON712", "speaker", "speaker", "EON", "12 in active"),
  item("jbl-eon715", "JBL", "EON715", "speaker", "speaker", "EON15", "15 in active"),
  item("jbl-prx912", "JBL", "PRX912", "speaker", "speaker", "PRX12", "12 in active"),
  item("jbl-prx", "JBL", "PRX915", "speaker", "speaker", "PRX", "15 in active"),
  item("jbl-c28", "JBL", "Control 28-1", "speaker", "speaker", "C28", "8 in install"),
  item("jbl-c25", "JBL", "Control 25-1", "speaker", "speaker", "C25", "5 in install"),
  item("jbl-cbt70", "JBL", "CBT 70J-1", "speaker", "speaker", "CBT", "column"),
  item("jbl-srx835", "JBL", "SRX835P", "speaker", "speaker", "SRX", "15 in 3-way"),
  item("la-112p", "L-Acoustics", "112P", "speaker", "speaker", "112P", "coaxial active"),
  item("la-x8", "L-Acoustics", "X8", "speaker", "speaker", "X8", "coaxial"),
  item("la-x12", "L-Acoustics", "X12", "speaker", "speaker", "X12", "coaxial"),
  item("la-a15", "L-Acoustics", "A15", "speaker", "speaker", "A15", "medium format"),
  item("la-kiva", "L-Acoustics", "Kiva II", "speaker", "speaker", "KIVA", "line array"),
  item("meyer-ultral", "Meyer Sound", "Ultra-X40", "speaker", "speaker", "UX40", "point source"),
  item("meyer-upj", "Meyer Sound", "UPJ-1P", "speaker", "speaker", "UPJ", "point source"),
  item("meyer-upq", "Meyer Sound", "UPQ-1P", "speaker", "speaker", "UPQ", "point source"),
  item("dandb-y7", "d&b audiotechnik", "Y7P", "speaker", "speaker", "Y7", "point source"),
  item("dandb-y10", "d&b audiotechnik", "Y10P", "speaker", "speaker", "Y10", "point source"),
  item("dandb-e8", "d&b audiotechnik", "E8", "speaker", "speaker", "E8", "point source"),
  item("dandb-8s", "d&b audiotechnik", "8S", "speaker", "speaker", "8S", "install"),
  item("dandb-12s", "d&b audiotechnik", "12S", "speaker", "speaker", "12S", "install"),
  item("bose-dm8c", "Bose", "DesignMax DM8C", "speaker", "speaker", "DM8", "8 in ceiling"),
  item("bose-dm5c", "Bose", "DesignMax DM5C", "speaker", "speaker", "DM5", "5 in ceiling"),
  item("bose-f1", "Bose", "F1 Model 812", "speaker", "speaker", "F1", "array"),
  item("bose-rmu", "Bose", "RoomMatch Utility RMU105", "speaker", "speaker", "RMU", "install"),
  item("rcf-art912", "RCF", "ART 912-A", "speaker", "speaker", "ART", "12 in active"),
  item("rcf-hdl6", "RCF", "HDL 6-A", "speaker", "speaker", "HDL", "line array"),
  item("martin-cdd12", "Martin Audio", "CDD12", "speaker", "speaker", "CDD", "12 in coaxial"),
  item("martin-cdd8", "Martin Audio", "CDD8", "speaker", "speaker", "CDD8", "8 in coaxial"),
  item("nexo-ps15", "Nexo", "PS15", "speaker", "speaker", "PS15", "point source"),
  item("nexo-geo", "Nexo", "GEO M10", "speaker", "speaker", "GEO", "line array"),
  item("turbo-iq15", "Turbosound", "iQ15", "speaker", "speaker", "IQ15", "15 in active"),
  item("atlas-fap82", "AtlasIED", "FAP82T", "speaker", "speaker", "FAP", "8 in ceiling"),
  item("atlas-sm82", "AtlasIED", "SM82T", "speaker", "speaker", "SM82", "8 in surface"),
  item("tannoy-vxp12", "Tannoy", "VXP 12", "speaker", "speaker", "VXP", "12 in active"),
  item("karray-kk102", "K-array", "Kobra KK102", "speaker", "speaker", "KK", "column"),
  item("community-r5", "Community", "R.5", "speaker", "speaker", "R5", "weather"),
  item("renkus-ic8", "Renkus-Heinz", "IC8-RN", "speaker", "speaker", "IC8", "steerable"),

  // Microphones
  item("shure-sm58", "Shure", "SM58", "microphone", "mic", "SM58", "dynamic vocal"),
  item("shure-sm57", "Shure", "SM57", "microphone", "mic", "SM57", "dynamic instrument"),
  item("shure-sm7b", "Shure", "SM7B", "microphone", "mic", "SM7B", "broadcast dynamic"),
  item("shure-beta58", "Shure", "Beta 58A", "microphone", "mic", "B58", "supercardioid vocal"),
  item("shure-beta57", "Shure", "Beta 57A", "microphone", "mic", "B57", "supercardioid"),
  item("shure-beta52", "Shure", "Beta 52A", "microphone", "mic", "B52", "kick"),
  item("shure-beta91", "Shure", "Beta 91A", "microphone", "mic", "B91", "boundary kick"),
  item("shure-ksm8", "Shure", "KSM8", "microphone", "mic", "KSM8", "dual-diaphragm vocal"),
  item("shure-ksm9", "Shure", "KSM9", "microphone", "mic", "KSM9", "condenser vocal"),
  item("shure-ksm32", "Shure", "KSM32", "microphone", "mic", "KSM", "condenser"),
  item("shure-ksm44", "Shure", "KSM44A", "microphone", "mic", "K44", "multi-pattern"),
  item("shure-mx418", "Shure", "MX418", "microphone", "mic", "MX18", "18 in gooseneck"),
  item("shure-mx202", "Shure", "MX202", "microphone", "mic", "MX202", "overhead"),
  item("shure-cvg18", "Shure", "CVG18", "microphone", "mic", "CVG", "gooseneck"),
  item("senn-e835", "Sennheiser", "e835", "microphone", "mic", "E835", "dynamic vocal"),
  item("senn-e845", "Sennheiser", "e845", "microphone", "mic", "E845", "supercardioid vocal"),
  item("senn-e865", "Sennheiser", "e865", "microphone", "mic", "E865", "condenser vocal"),
  item("senn-e935", "Sennheiser", "e935", "microphone", "mic", "E935", "dynamic vocal"),
  item("senn-e945", "Sennheiser", "e945", "microphone", "mic", "E945", "supercardioid vocal"),
  item("senn-e604", "Sennheiser", "e604", "microphone", "mic", "E604", "tom / snare"),
  item("senn-e609", "Sennheiser", "e609", "microphone", "mic", "E609", "guitar cab"),
  item("senn-e901", "Sennheiser", "e901", "microphone", "mic", "E901", "boundary kick"),
  item("senn-e902", "Sennheiser", "e902", "microphone", "mic", "E902", "kick"),
  item("senn-md421", "Sennheiser", "MD 421-II", "microphone", "mic", "421", "dynamic"),
  item("senn-md441", "Sennheiser", "MD 441-U", "microphone", "mic", "441", "dynamic"),
  item("senn-mkh416", "Sennheiser", "MKH 416", "microphone", "mic", "416", "shotgun"),
  item("at-at2020", "Audio-Technica", "AT2020", "microphone", "mic", "2020", "side-address condenser"),
  item("at-at2035", "Audio-Technica", "AT2035", "microphone", "mic", "2035", "cardioid condenser"),
  item("at-at4040", "Audio-Technica", "AT4040", "microphone", "mic", "4040", "studio condenser"),
  item("at-at4050", "Audio-Technica", "AT4050", "microphone", "mic", "4050", "multi-pattern"),
  item("at-ae4100", "Audio-Technica", "AE4100", "microphone", "mic", "AE41", "vocal condenser"),
  item("at-ae6100", "Audio-Technica", "AE6100", "microphone", "mic", "AE61", "hypercardioid vocal"),
  item("at-pro61", "Audio-Technica", "PRO 61", "microphone", "mic", "P61", "vocal dynamic"),
  item("at-u851r", "Audio-Technica", "U851R", "microphone", "mic", "U851", "boundary"),
  item("akg-d5", "AKG", "D5", "microphone", "mic", "D5", "dynamic vocal"),
  item("akg-d7", "AKG", "D7", "microphone", "mic", "D7", "dynamic vocal"),
  item("akg-c414", "AKG", "C414 XLII", "microphone", "mic", "C414", "multi-pattern"),
  item("akg-c451", "AKG", "C451 B", "microphone", "mic", "C451", "small condenser"),
  item("akg-p5", "AKG", "P5", "microphone", "mic", "P5", "dynamic vocal"),
  item("rode-nt1", "RØDE", "NT1 5th Gen", "microphone", "mic", "NT1", "studio condenser"),
  item("rode-nt2", "RØDE", "NT2-A", "microphone", "mic", "NT2", "multi-pattern"),
  item("rode-m5", "RØDE", "M5", "microphone", "mic", "M5", "small condenser pair"),
  item("rode-podmic", "RØDE", "PodMic", "microphone", "mic", "POD", "broadcast dynamic"),
  item("neumann-kms105", "Neumann", "KMS 105", "microphone", "mic", "KMS", "condenser vocal"),
  item("neumann-km184", "Neumann", "KM 184", "microphone", "mic", "KM184", "small condenser"),
  item("neumann-tlm103", "Neumann", "TLM 103", "microphone", "mic", "TLM", "studio condenser"),
  item("neumann-u87", "Neumann", "U 87 Ai", "microphone", "mic", "U87", "studio condenser"),
  item("dpa-4099", "DPA", "4099", "microphone", "mic", "4099", "instrument clip"),
  item("dpa-2011", "DPA", "2011C", "microphone", "mic", "2011", "cardioid compact"),
  item("dpa-4066", "DPA", "4066", "microphone", "mic", "4066", "headset"),
  item("dpa-4288", "DPA", "4288", "microphone", "mic", "4288", "headset directional"),
  item("audix-om5", "Audix", "OM5", "microphone", "mic", "OM5", "vocal dynamic"),
  item("audix-om7", "Audix", "OM7", "microphone", "mic", "OM7", "vocal dynamic"),
  item("audix-i5", "Audix", "i5", "microphone", "mic", "I5", "instrument"),
  item("audix-d6", "Audix", "D6", "microphone", "mic", "D6", "kick"),
  item("beyer-m88", "Beyerdynamic", "M 88 TG", "microphone", "mic", "M88", "dynamic"),
  item("beyer-tgv70", "Beyerdynamic", "TG V70d", "microphone", "mic", "V70", "vocal dynamic"),
  item("beyer-mc930", "Beyerdynamic", "MC 930", "microphone", "mic", "MC93", "small condenser"),
  item("lewitt-mtp550", "Lewitt", "MTP 550 DM", "microphone", "mic", "MTP", "vocal dynamic"),
  item("lewitt-lct440", "Lewitt", "LCT 440 PURE", "microphone", "mic", "LCT", "studio condenser"),
  item("earthworks-sr20", "Earthworks", "SR20", "microphone", "mic", "SR20", "vocal condenser"),
  item("earthworks-qtc40", "Earthworks", "QTC40", "microphone", "mic", "QTC", "omni condenser"),
  item("heil-pr35", "Heil", "PR 35", "microphone", "mic", "PR35", "vocal dynamic"),
  item("heil-pr40", "Heil", "PR 40", "microphone", "mic", "PR40", "broadcast dynamic"),
  item("ev-re20", "Electro-Voice", "RE20", "microphone", "mic", "RE20", "broadcast dynamic"),
  item("ev-nd767", "Electro-Voice", "ND767a", "microphone", "mic", "ND76", "vocal dynamic"),
  item("countryman-h6", "Countryman", "H6", "microphone", "mic", "H6", "headset"),
  item("countryman-e6", "Countryman", "E6", "microphone", "mic", "E6", "earset"),
  item("clock-c003", "Clockaudio", "C 003E", "microphone", "mic", "C003", "boundary"),

  // Wireless
  item("shure-slxd24", "Shure", "SLXD24/SM58", "wireless", "shure", "SLXD", "digital handheld"),
  item("shure-slxd4d", "Shure", "SLXD4D", "wireless", "shure", "SLX2", "dual receiver"),
  item("shure-qlxd", "Shure", "QLXD24/B58", "wireless", "shure", "QLXD", "digital handheld"),
  item("shure-ulxd", "Shure", "ULXD4D", "wireless", "shure", "ULXD", "dual receiver"),
  item("shure-ulxd4q", "Shure", "ULXD4Q", "wireless", "shure", "ULXQ", "quad receiver"),
  item("shure-ad4d", "Shure", "AD4D Axient Digital", "wireless", "shure", "AD4D", "dual receiver"),
  item("shure-glxd", "Shure", "GLXD24+", "wireless", "shure", "GLXD", "digital handheld"),
  item("shure-blx24", "Shure", "BLX24/SM58", "wireless", "shure", "BLX", "handheld"),
  item("shure-mxwapt8", "Shure", "MXWAPT8", "wireless", "shure", "MXW", "8 ch access point"),
  item("shure-psm1000", "Shure", "PSM 1000", "wireless", "shure", "PSM", "IEM dual"),
  item("shure-psm300", "Shure", "PSM 300", "wireless", "shure", "PSM3", "IEM stereo"),
  item("senn-ewd", "Sennheiser", "EW-D 835-S", "wireless", "shure", "EWD", "digital vocal"),
  item("senn-ewdx", "Sennheiser", "EW-DX 835-S", "wireless", "shure", "EWDX", "digital vocal"),
  item("senn-xsw1", "Sennheiser", "XSW 1-825", "wireless", "shure", "XSW", "vocal set"),
  item("senn-xsw2", "Sennheiser", "XSW 2-835", "wireless", "shure", "XSW2", "vocal set"),
  item("senn-2000", "Sennheiser", "2000 SKM 5200", "wireless", "shure", "2K", "handheld"),
  item("senn-6000", "Sennheiser", "Digital 6000", "wireless", "shure", "D6K", "dual receiver"),
  item("senn-iemg4", "Sennheiser", "EK IEM G4", "wireless", "shure", "IEM", "IEM bodypack"),
  item("at-system10", "Audio-Technica", "System 10 PRO", "wireless", "shure", "S10", "digital"),
  item("at-3000", "Audio-Technica", "3000 Series", "wireless", "shure", "AT3K", "handheld"),
  item("at-5000", "Audio-Technica", "5000 Series", "wireless", "shure", "AT5K", "dual receiver"),
  item("lectro-dsr4", "Lectrosonics", "DSR4", "wireless", "shure", "DSR4", "4 ch digital"),
  item("lectro-hh", "Lectrosonics", "HH", "wireless", "shure", "LHH", "handheld"),
  item("line6-xdv75", "Line 6", "XD-V75", "wireless", "shure", "XDV", "digital handheld"),

  // Cameras
  item("ptz-formako", "Formako", "UHK-X700", "camera", "camera", "PTZ", "20× NDI|HX"),
  item("ptz-optics-move", "PTZOptics", "Move 4K", "camera", "camera", "MOVE", "4K 20×"),
  item("ptz-optics-se", "PTZOptics", "Move SE", "camera", "camera", "SE", "1080p 20×"),
  item("ptz-optics-link", "PTZOptics", "Link 4K", "camera", "camera", "LINK", "4K SDI/HDMI"),
  item("ptz-studio", "PTZOptics", "Studio Pro", "camera", "camera", "STUD", "NDI studio"),
  item("birddog-p200", "BirdDog", "P200", "camera", "camera", "P200", "NDI PTZ"),
  item("birddog-p4k", "BirdDog", "P4K", "camera", "camera", "P4K", "4K NDI"),
  item("birddog-x1", "BirdDog", "X1 Ultra", "camera", "camera", "X1", "4K NDI"),
  item("birddog-a200", "BirdDog", "A200", "camera", "camera", "A200", "NDI|HX"),
  item("sony-brc", "Sony", "BRC-X400", "camera", "camera", "X400", "4K PTZ"),
  item("sony-am7", "Sony", "BRC-AM7", "camera", "camera", "AM7", "4K PTZ"),
  item("sony-ilme", "Sony", "ILME-FR7", "camera", "camera", "FR7", "full-frame PTZ"),
  item("sony-srg", "Sony", "SRG-X120", "camera", "camera", "X120", "4K PTZ"),
  item("panasonic-ue150", "Panasonic", "AW-UE150", "camera", "camera", "UE150", "4K 20×"),
  item("panasonic-ue80", "Panasonic", "AW-UE80", "camera", "camera", "UE80", "4K 24×"),
  item("panasonic-ue50", "Panasonic", "AW-UE50", "camera", "camera", "UE50", "4K 24×"),
  item("aver-ptc", "AVer", "PTC310UV2", "camera", "camera", "PTC", "4K tracking"),
  item("aver-tr315", "AVer", "TR315", "camera", "camera", "TR315", "auto-track"),
  item("logitech-rally", "Logitech", "Rally Camera", "camera", "camera", "RALLY", "PTZ conferencing"),
  item("logitech-meetup", "Logitech", "Meetup", "camera", "camera", "MEET", "conference cam"),
  item("canon-crn500", "Canon", "CR-N500", "camera", "camera", "N500", "4K PTZ"),
  item("canon-crn300", "Canon", "CR-N300", "camera", "camera", "N300", "4K PTZ"),
  item("marshall-cv605", "Marshall", "CV605-U3", "camera", "camera", "CV605", "USB PTZ"),
  item("lumens-vca71", "Lumens", "VC-A71PN", "camera", "camera", "A71", "4K NDI"),

  // Displays
  item("samsung-qm85", "Samsung", "QM85C", "display", "display", "85\"", "85 in 4K"),
  item("samsung-qm75", "Samsung", "QM75C", "display", "display", "75\"", "75 in 4K"),
  item("samsung-qm55", "Samsung", "QM55C", "display", "display", "55\"", "55 in 4K"),
  item("samsung-qb85", "Samsung", "QB85C", "display", "display", "85\"", "85 in 4K"),
  item("samsung-qb", "Samsung", "QB75C", "display", "display", "75\"", "75 in 4K"),
  item("lg-uh5", "LG", "86UH5J-H", "display", "display", "86\"", "86 in UHD"),
  item("lg-uh575", "LG", "75UH5J-H", "display", "display", "75\"", "75 in UHD"),
  item("lg-ul3", "LG", "55UL3J-M", "display", "display", "55\"", "55 in UHD"),
  item("lg-ul386", "LG", "86UL3J-B", "display", "display", "86\"", "86 in UHD"),
  item("sony-bz40", "Sony", "FW-85BZ40H", "display", "display", "85\"", "85 in 4K BRAVIA"),
  item("sony-bz75", "Sony", "FW-75BZ40H", "display", "display", "75\"", "75 in 4K"),
  item("sony-bz55", "Sony", "FW-55BZ40H", "display", "display", "55\"", "55 in 4K"),
  item("nec-m861", "Sharp / NEC", "M861", "display", "display", "86\"", "86 in 4K"),
  item("nec-m751", "Sharp / NEC", "M751", "display", "display", "75\"", "75 in 4K"),
  item("nec-m551", "Sharp / NEC", "M551", "display", "display", "55\"", "55 in 4K"),
  item("planar-qe98", "Planar", "QE9850", "display", "display", "98\"", "98 in 4K"),
  item("dell-p2422", "Dell", "P2422H", "display", "monitor", "MON", "24 in FHD"),
  item("dell-p2723", "Dell", "P2723DE", "display", "monitor", "MON27", "27 in QHD"),
  item("lg-27un", "LG", "27UN850", "display", "monitor", "MON4K", "27 in 4K"),
  item("hisense-86wr", "Hisense", "86WR6BE", "display", "display", "86\"", "86 in 4K"),
  item("philips-86bdl", "Philips", "86BDL3650Q", "display", "display", "86\"", "86 in 4K"),

  // Conferencing
  item("neat-bar", "Neat", "Bar", "conference", "neatbar", "NB", "soundbar + 4K"),
  item("neat-barpro", "Neat", "Bar Pro", "conference", "neatbar", "NBP", "wide FOV bar"),
  item("neat-pad", "Neat", "Pad", "conference", "neatpad", "PAD", "touch controller"),
  item("neat-board50", "Neat", "Board 50", "conference", "display", "BRD", "50 in collab"),
  item("neat-board65", "Neat", "Board 65", "conference", "display", "BRD65", "65 in collab"),
  item("neat-frame", "Neat", "Frame", "conference", "display", "FRM", "framed display"),
  item("logi-rallybar", "Logitech", "Rally Bar", "conference", "neatbar", "RB", "all-in-one"),
  item("logi-rallybarm", "Logitech", "Rally Bar Mini", "conference", "neatbar", "RBM", "huddle"),
  item("logi-rallyh", "Logitech", "Rally Bar Huddle", "conference", "neatbar", "RBH", "huddle"),
  item("logi-tapip", "Logitech", "Tap IP", "conference", "zoomctrl", "TAPIP", "PoE tap"),
  item("yealink-a20", "Yealink", "MeetingBar A20", "conference", "neatbar", "A20", "huddle bar"),
  item("yealink-a30", "Yealink", "MeetingBar A30", "conference", "neatbar", "A30", "medium room"),
  item("yealink-a50", "Yealink", "MeetingBar A50", "conference", "neatbar", "A50", "large room"),
  item("cisco-kit", "Cisco", "Room Kit EQ", "conference", "neatbar", "EQ", "codec + cam"),
  item("cisco-barpro", "Cisco", "Room Bar Pro", "conference", "neatbar", "RBP", "video bar"),
  item("cisco-board75", "Cisco", "Webex Board Pro 75", "conference", "display", "WB75", "75 in collab"),
  item("poly-studio", "Poly", "Studio X50", "conference", "neatbar", "X50", "video bar"),
  item("poly-x70", "Poly", "Studio X70", "conference", "neatbar", "X70", "video bar"),
  item("crestron-ucb", "Crestron", "UC-B160-T", "conference", "neatbar", "UCB", "Teams bar"),
  item("barco-cx50", "Barco", "ClickShare CX-50", "conference", "splitter", "CX50", "wireless share"),
  item("dten-me55", "DTEN", "Me 55", "conference", "display", "DTEN", "55 in Zoom"),

  // Network
  item("cisco-cbs250", "Cisco", "CBS250-8P-E-2G", "network", "netswitch", "CBS", "8 port PoE+"),
  item("cisco-cbs350", "Cisco", "CBS350-24P", "network", "netswitch", "C350", "24 port PoE+"),
  item("cisco-c9200", "Cisco", "C9200-24P", "network", "netswitch", "C9200", "24 port PoE+"),
  item("cisco-c1000", "Cisco", "C1000-8P", "network", "netswitch", "C1K", "8 port PoE"),
  item("ubnt-usw8", "Ubiquiti", "USW-Lite-8-PoE", "network", "netswitch", "USW", "8 port PoE"),
  item("ubnt-usw24", "Ubiquiti", "USW-Pro-24-PoE", "network", "netswitch", "USW24", "24 port PoE"),
  item("ubnt-uswent", "Ubiquiti", "USW-Enterprise-24-PoE", "network", "netswitch", "USWE", "2.5G PoE"),
  item("ubnt-flex", "Ubiquiti", "USW-Flex", "network", "netswitch", "FLEX", "5 port PoE"),
  item("netgear-gs110", "Netgear", "GS110TPv3", "network", "netswitch", "GS110", "8 port PoE+"),
  item("netgear-m4250", "Netgear", "M4250-9G2XF-PoE+", "network", "netswitch", "AVSW", "AV Line"),
  item("netgear-gsm4210", "Netgear", "GSM4210P", "network", "netswitch", "GSM", "8 port AV"),
  item("tplink-sg108", "TP-Link", "TL-SG108PE", "network", "netswitch", "SG8", "8 port PoE"),
  item("tplink-sg3428", "TP-Link", "SG3428MP", "network", "netswitch", "SG28", "24 port PoE+"),
  item("luxul-ams", "Luxul", "AMS-1816P", "network", "netswitch", "AMS", "16 port AV"),
  item("luxul-ams26", "Luxul", "AMS-2616P", "network", "netswitch", "AMS26", "16 port AV"),
  item("luminex-gc16", "Luminex", "GigaCore 16R", "network", "netswitch", "GC16", "AV Ethernet"),
  item("luminex-gc10", "Luminex", "GigaCore 10", "network", "netswitch", "GC10", "AV Ethernet"),
  item("aruba-2930", "Aruba", "2930F 24G PoE+", "network", "netswitch", "2930", "24 port PoE+"),

  // DSP
  item("qsys-core8", "Q-SYS", "Core 8 Flex", "dsp", "dsp", "C8F", "software DSP"),
  item("qsys-nano", "Q-SYS", "Core Nano", "dsp", "dsp", "NANO", "network DSP"),
  item("qsys-core110", "Q-SYS", "Core 110f", "dsp", "dsp", "C110", "network I/O"),
  item("qsys-core510", "Q-SYS", "Core 510i", "dsp", "dsp", "C510", "install DSP"),
  item("qsys-nv32", "Q-SYS", "NV-32-H", "dsp", "dsp", "NV32", "HDMI I/O"),
  item("biamp-tesira", "Biamp", "TesiraFORTÉ DAN", "dsp", "dsp", "TF", "Dante DSP"),
  item("biamp-x1600", "Biamp", "TesiraFORTÉ X 1600", "dsp", "dsp", "TFX", "USB-C DSP"),
  item("biamp-server", "Biamp", "Tesira SERVER-IO", "dsp", "dsp", "SRV", "modular DSP"),
  item("biamp-devio", "Biamp", "Devio SCX 400", "dsp", "dsp", "SCX", "huddle DSP"),
  item("dbx-venu", "dbx", "DriveRack VENU360", "dsp", "dsp", "VENU", "loudspeaker management"),
  item("dbx-pa2", "dbx", "DriveRack PA2", "dsp", "dsp", "PA2", "speaker processor"),
  item("bss-blu", "BSS", "BLU-100", "dsp", "dsp", "BLU", "Soundweb London"),
  item("bss-blu50", "BSS", "BLU-50", "dsp", "dsp", "BLU50", "I/O expander"),
  item("bss-blu160", "BSS", "BLU-160", "dsp", "dsp", "BLU16", "open architecture"),
  item("bss-blu800", "BSS", "BLU-800", "dsp", "dsp", "BLU80", "flagship DSP"),
  item("yamaha-mtx3", "Yamaha", "MTX3", "dsp", "dsp", "MTX", "matrix processor"),
  item("yamaha-mtx5", "Yamaha", "MTX5-D", "dsp", "dsp", "MTX5", "Dante matrix"),
  item("yamaha-mrx7", "Yamaha", "MRX7-D", "dsp", "dsp", "MRX", "open architecture"),
  item("yamaha-dme7", "Yamaha", "DME7", "dsp", "dsp", "DME7", "system processor"),
  item("symetrix-prism", "Symetrix", "Prism 8x8", "dsp", "dsp", "PRSM", "8×8 DSP"),
  item("symetrix-radius", "Symetrix", "Radius NX 4×4", "dsp", "dsp", "RAD", "Dante DSP"),
  item("bose-esp880", "Bose", "ControlSpace ESP-880A", "dsp", "dsp", "ESP", "8×8 DSP"),
  item("bose-ex1280", "Bose", "ControlSpace EX-1280C", "dsp", "dsp", "EX12", "conferencing DSP"),
  item("xilica-solaro", "Xilica", "Solaro QR1", "dsp", "dsp", "QR1", "network DSP"),
  item("peavey-nion", "Peavey", "MediaMatrix NION n3", "dsp", "dsp", "NION", "media matrix"),
  item("lake-lm44", "Lake", "LM 44", "dsp", "dsp", "LM44", "loudspeaker processor"),

  // Control
  item("ptzoptics-superjoy", "PTZOptics", "SuperJoy", "control", "ptzctrl", "SJ", "PTZ joystick"),
  item("ptzoptics-jr", "PTZOptics", "SuperJoy Jr", "control", "ptzctrl", "SJJ", "compact joystick"),
  item("sony-rmip10", "Sony", "RM-IP10", "control", "ptzctrl", "IP10", "IP joystick"),
  item("sony-rmip500", "Sony", "RM-IP500", "control", "ptzctrl", "IP500", "IP joystick"),
  item("panasonic-rp150", "Panasonic", "AW-RP150", "control", "ptzctrl", "RP150", "PTZ controller"),
  item("panasonic-rp60", "Panasonic", "AW-RP60", "control", "ptzctrl", "RP60", "compact PTZ"),
  item("logi-tap", "Logitech", "Tap", "control", "zoomctrl", "TAP", "Zoom/Teams tap"),
  item("logi-scribe", "Logitech", "Scribe", "control", "zoomsched", "SCR", "whiteboard cam"),
  item("crestron-ts", "Crestron", "TS-1070", "control", "zoomctrl", "TS10", "10 in touch"),
  item("crestron-tsw", "Crestron", "TSW-1070", "control", "zoomctrl", "TSW", "10 in wall"),
  item("crestron-cp4n", "Crestron", "CP4N", "control", "zoomctrl", "CP4N", "4-series processor"),
  item("extron-tlp", "Extron", "TLP Pro 1025T", "control", "zoomctrl", "TLP", "10 in touch"),
  item("extron-ipcp", "Extron", "IPCP Pro 550", "control", "zoomctrl", "IPCP", "control processor"),
  item("amx-mxt", "AMX", "MXT-1001", "control", "zoomctrl", "MXT", "10 in tabletop"),
  item("qsys-tsc101", "Q-SYS", "TSC-101-G3", "control", "zoomctrl", "TSC10", "10 in PoE"),
  item("qsys-tsc70", "Q-SYS", "TSC-70-G3", "control", "zoomctrl", "TSC7", "7 in PoE"),

  // Racks
  item("ma-wrk", "Middle Atlantic", "WRK-44-32", "rack", "rack", "WRK", "44U gangable"),
  item("ma-dwr", "Middle Atlantic", "DWR-18-26", "rack", "rack", "DWR", "18U wall"),
  item("ma-erk", "Middle Atlantic", "ERK-2124", "rack", "rack", "ERK", "21U"),
  item("ma-sr40", "Middle Atlantic", "SR-40-22", "rack", "rack", "SR40", "40U slim"),
  item("penn-r1264", "Penn Elcom", "R1264/19UK", "rack", "rack", "R12", "12U"),
  item("skb-r6", "SKB", "Roto-Molded 6U", "rack", "rack", "6U", "shock rack"),
  item("skb-r12", "SKB", "1SKB19-R1206U", "rack", "rack", "12U", "shock rack"),
  item("gator-gr12", "Gator", "GR-12L", "rack", "rack", "GR12", "12U"),
  item("gator-grw10", "Gator", "GRW-10HD", "rack", "rack", "GRW", "10U wall"),
  item("chief-cfr", "Chief", "CFR-211", "rack", "rack", "CFR", "component rack"),

  // Power
  item("furman-pl", "Furman", "PL-8 C E", "power", "pdu", "PL8", "conditioner"),
  item("furman-p2400", "Furman", "P-2400 AR E", "power", "pdu", "P24", "voltage regulator"),
  item("furman-cn1800", "Furman", "CN-1800S", "power", "pdu", "CN18", "smart sequencer"),
  item("furman-f1500", "Furman", "F1500-UPS E", "power", "pdu", "UPS", "1.5 kVA UPS"),
  item("tripplite-pdumh", "Eaton / Tripp Lite", "PDUMH15", "power", "pdu", "PDU", "metered 1U"),
  item("eaton-9px", "Eaton", "9PX 1500", "power", "pdu", "9PX", "1.5 kVA UPS"),
  item("apc-smt", "APC", "SMT1500RM2U", "power", "pdu", "SMT", "1.5 kVA UPS"),
  item("apc-ap7921", "APC", "AP7921", "power", "pdu", "AP79", "switched PDU"),
  item("surgex-sx", "SurgeX", "SX1115RT", "power", "pdu", "SX", "conditioner"),
  item("legrand-wiremold", "Legrand", "Wiremold 2400", "power", "outlet", "WM", "surface raceway"),
  item("legrand-quad", "Legrand", "Pass & Seymour 15A", "power", "outlet", "R", "duplex outlet"),
  item("wattbox-800", "WattBox", "WB-800-IPVM-12", "power", "pdu", "WB", "12-outlet IP"),
  item("juice-cq1", "Juice Goose", "CQ-1", "power", "pdu", "CQ1", "sequencer"),

  // Cables
  item("belden-1305a", "Belden", "1305A Cat6", "cable", undefined, "C6", "UTP CMR", "cat6"),
  item("belden-10gxs", "Belden", "10GXS Cat6A", "cable", undefined, "C6A", "10G UTP", "cat6"),
  item("belden-1694a", "Belden", "1694A", "cable", undefined, "SDI", "3G-SDI coax", "sdi"),
  item("belden-1800f", "Belden", "1800F AES", "cable", undefined, "AES", "AES3 digital", "xlr"),
  item("belden-5100ue", "Belden", "5100UE", "cable", undefined, "SPK", "12 AWG speaker", "power"),
  item("belden-1502r", "Belden", "1502R", "cable", undefined, "MIC", "mic cable", "xlr"),
  item("canare-l4e6s", "Canare", "L-4E6S", "cable", undefined, "STAR", "star-quad mic", "xlr"),
  item("canare-l2t2s", "Canare", "L-2T2S", "cable", undefined, "L2T", "mic / line", "xlr"),
  item("canare-lv61s", "Canare", "LV-61S", "cable", undefined, "VID", "75 Ω video", "sdi"),
  item("canare-4s11", "Canare", "4S11", "cable", undefined, "4S11", "speaker", "power"),
  item("mogami-2534", "Mogami", "W2534", "cable", undefined, "MOG", "quad mic", "xlr"),
  item("mogami-2931", "Mogami", "W2931", "cable", undefined, "M293", "mic cable", "xlr"),
  item("mogami-3080", "Mogami", "W3080", "cable", undefined, "M308", "speaker", "power"),
  item("neutrik-xlr", "Neutrik", "NC3MXX / NC3FXX", "cable", undefined, "XLR", "3-pin XLR", "xlr"),
  item("neutrik-nl4", "Neutrik", "speakON NL4FX", "cable", undefined, "NL4", "loudspeaker", "power"),
  item("neutrik-nac3", "Neutrik", "powerCON NAC3FCA", "cable", undefined, "PCN", "powerCON", "power"),
  item("neutrik-ether", "Neutrik", "etherCON NE8MC", "cable", undefined, "EC", "RJ45 shell", "cat6"),
  item("extron-hdmi-cable", "Extron", "HDMI Ultra/6", "cable", undefined, "HDMI", "HDMI 2.0 1.8 m", "hdmi"),
  item("extron-hdmi12", "Extron", "HDMI Pro/12", "cable", undefined, "HD12", "HDMI 3.6 m", "hdmi"),
  item("extron-xtp", "Extron", "XTP DTP 24", "cable", undefined, "DTP", "shielded AV UTP", "cat6"),
  item("kramer-hdmi", "Kramer", "C-HM/HM-10", "cable", undefined, "KHM", "HDMI 3 m", "hdmi"),
  item("krell-usb", "Kramer", "C-USB/AA-10", "cable", undefined, "USB", "USB-A 3 m", "usb"),
  item("sommer-cicada", "Sommer", "SC-Cicada", "cable", undefined, "CIC", "mic cable", "xlr"),
  item("sommer-goblin", "Sommer", "SC-Goblin", "cable", undefined, "GOB", "multicore", "xlr"),
  item("vandamme-xke", "Van Damme", "Tour Grade Classic XKE", "cable", undefined, "XKE", "starquad", "xlr"),
  item("whirlwind-mk4", "Whirlwind", "MK4", "cable", undefined, "MK4", "mic cable", "xlr"),
  item("rapco-m1", "RapcoHorizon", "M1", "cable", undefined, "M1", "mic cable", "xlr"),
  item("liberty-16-2", "Liberty", "16-2C-P", "cable", undefined, "16/2", "speaker plenum", "power"),
  item("liberty-22-2", "Liberty", "22-2P-P", "cable", undefined, "22/2", "control pair", "usb"),
  item("crestron-dm8g", "Crestron", "DM-CBL-8G-NP", "cable", undefined, "DM8G", "DigitalMedia", "hdmi"),
  item("gepco-ga714", "Gepco", "GA714", "cable", undefined, "GA7", "AES digital", "xlr"),
  item("gator-power", "Gator", "GTR-PWR-15", "cable", undefined, "IEC", "IEC power 15A", "power"),
  item("generic-cat6", "Generic", "Cat6 UTP 305 m box", "cable", undefined, "C6", "CMR UTP", "cat6"),
  item("generic-cat6a", "Generic", "Cat6A UTP", "cable", undefined, "C6A", "10G UTP", "cat6"),
  item("generic-hdmi21", "Generic", "HDMI 2.1 10 m", "cable", undefined, "HDMI", "48 Gbps", "hdmi"),
  item("generic-xlr10", "Generic", "XLR 10 m", "cable", undefined, "XLR", "mic / line", "xlr"),
  item("generic-usbc", "Generic", "USB-C 3 m", "cable", undefined, "USBC", "USB 3.1", "usb"),
  item("generic-speakon", "Generic", "speakON 10 m", "cable", undefined, "NL4", "2-core speaker", "power"),
  item("generic-sdi15", "Generic", "3G-SDI 15 m", "cable", undefined, "SDI", "75 Ω BNC", "sdi"),
  item("generic-sdi12g", "Generic", "12G-SDI 10 m", "cable", undefined, "12G", "4K BNC", "sdi"),
  item("belden-1505a", "Belden", "1505A", "cable", undefined, "SDI", "HD-SDI coax", "sdi"),
  item("canare-l5cfb", "Canare", "L-5CFB", "cable", undefined, "L5C", "75 Ω SDI", "sdi"),
  item("generic-dante", "Generic", "Dante / AES67 Cat6", "cable", undefined, "DAN", "AoIP", "cat6"),

  // Stage
  item("pearl-export", "Pearl", "Export 5-piece", "stage", "drums", "DR", "drum kit"),
  item("yamaha-stagec", "Yamaha", "Stage Custom", "stage", "drums", "DR", "drum kit"),
  item("dw-perf", "DW", "Performance", "stage", "drums", "DW", "drum kit"),
  item("nord-stage", "Nord", "Stage 4 88", "stage", "keys", "KEY", "stage piano"),
  item("nord-electro", "Nord", "Electro 6D 73", "stage", "keys", "NE6", "stage keys"),
  item("yamaha-cp88", "Yamaha", "CP88", "stage", "keys", "KEY", "stage piano"),
  item("yamaha-p125", "Yamaha", "P-125", "stage", "keys", "P125", "digital piano"),
  item("roland-rd88", "Roland", "RD-88", "stage", "keys", "KEY", "stage piano"),
  item("roland-rd2000", "Roland", "RD-2000", "stage", "keys", "RD2K", "stage piano"),

  // HDMI splitters, matrices, switchers
  item("kramer-vm2h", "Kramer", "VM-2H", "accessory", "splitter", "VM2", "HDMI 1×2 splitter"),
  item("kramer-vm4h", "Kramer", "VM-4H", "accessory", "splitter", "VM4", "HDMI 1×4 splitter"),
  item("kramer-vm", "Kramer", "VM-8H", "accessory", "splitter", "VM8", "HDMI 1×8 splitter"),
  item("kramer-vm16h", "Kramer", "VM-16H", "accessory", "splitter", "VM16", "HDMI 1×16 splitter"),
  item("kramer-vm4h2", "Kramer", "VM-4H2", "accessory", "splitter", "VM4H", "4K HDMI 1×4 splitter"),
  item("kramer-vm8h2", "Kramer", "VM-8H2", "accessory", "splitter", "VM8H", "4K HDMI 1×8 splitter"),
  item("kramer-vm2hxl", "Kramer", "VM-2Hxl", "accessory", "splitter", "VM2X", "HDMI 1×2 DA"),
  item("extron-da2", "Extron", "DA2 HD 4K", "accessory", "splitter", "DA2", "HDMI 1×2 DA"),
  item("extron-da4", "Extron", "DA4 HD 4K PLUS", "accessory", "splitter", "DA4", "HDMI 1×4 DA"),
  item("extron-da6", "Extron", "DA6 HD 4K PLUS", "accessory", "splitter", "DA6", "HDMI 1×6 DA"),
  item("extron-hdmi", "Extron", "HD 4K 101", "accessory", "splitter", "HD4K", "4K HDMI DA"),
  item("extron-hdxa", "Extron", "HD 4K 101 Plus", "accessory", "splitter", "HD101", "4K HDMI DA + audio"),
  item("extron-dtpda4", "Extron", "DTP HD DA4 4K 230", "accessory", "splitter", "DTP4", "HDBaseT 1×4 DA"),
  item("extron-dtpda8", "Extron", "DTP HD DA8 4K 230", "accessory", "splitter", "DTP8", "HDBaseT 1×8 DA"),
  item("aten-vs182a", "ATEN", "VS182A", "accessory", "splitter", "182A", "HDMI 1×2 splitter"),
  item("aten-vs184a", "ATEN", "VS184A", "accessory", "splitter", "184A", "HDMI 1×4 splitter"),
  item("aten-vs", "ATEN", "VS0108HB", "accessory", "splitter", "SPL", "HDMI 1×8 splitter"),
  item("aten-vs0116", "ATEN", "VS0116HB", "accessory", "splitter", "VS16", "HDMI 1×16 splitter"),
  item("aten-vs182b", "ATEN", "VS182B", "accessory", "splitter", "182B", "4K HDMI 1×2 splitter"),
  item("aten-vs184b", "ATEN", "VS184B", "accessory", "splitter", "184B", "4K HDMI 1×4 splitter"),
  item("kd-sp2x4", "Key Digital", "KD-SP2x4", "accessory", "splitter", "SP24", "HDMI 1×4 splitter"),
  item("kd-sp2x8", "Key Digital", "KD-SP2x8", "accessory", "splitter", "SP28", "HDMI 1×8 splitter"),
  item("wyre-spl0104", "WyreStorm", "SPL-0104-H2", "accessory", "splitter", "W104", "HDMI 1×4 4K splitter"),
  item("wyre-spl0108", "WyreStorm", "SPL-0108-H2", "accessory", "splitter", "W108", "HDMI 1×8 4K splitter"),
  item("gefen-uhd144", "Gefen", "EXT-UHD-144", "accessory", "splitter", "G144", "4K HDMI 1×4 splitter"),
  item("gefen-hdmi142", "Gefen", "GTV-HDMI1.3-142", "accessory", "splitter", "G142", "HDMI 1×2 splitter"),
  item("bmd-hdmi-dist", "Blackmagic", "Mini Converter HDMI Distribution", "accessory", "splitter", "HMD", "HDMI DA"),
  item("kanex-hdsp18", "KanexPro", "HDSP18", "accessory", "splitter", "K18", "HDMI 1×8 splitter"),
  item("kanex-hdsp14", "KanexPro", "HDSP14", "accessory", "splitter", "K14", "HDMI 1×4 splitter"),
  item("mono-bb4", "Monoprice", "Blackbird 4K 1x4", "accessory", "splitter", "BB4", "HDMI 1×4 splitter"),
  item("mono-bb8", "Monoprice", "Blackbird 4K 1x8", "accessory", "splitter", "BB8", "HDMI 1×8 splitter"),
  item("hall-uh1d8", "Hall Research", "UH-1D-8", "accessory", "splitter", "UH8", "HDMI 1×8 splitter"),
  item("crestron-hdda2", "Crestron", "HD-DA-2", "accessory", "splitter", "DA2C", "HDMI 1×2 DA"),
  item("crestron-hdda4", "Crestron", "HD-DA-4", "accessory", "splitter", "DA4C", "HDMI 1×4 DA"),
  item("binary-hdsp", "Binary", "B-200-HDSP-4K", "accessory", "splitter", "B4K", "HDMI 1×4 splitter"),
  item("pulse8-sp4", "Pulse-Eight", "neo HDMI 1x4", "accessory", "splitter", "P84", "HDMI 1×4 splitter"),
  item("generic-hdmi-sp4", "Generic", "HDMI 1×4 splitter 4K", "accessory", "splitter", "HSP4", "HDMI 1×4 splitter"),
  item("generic-hdmi-sp8", "Generic", "HDMI 1×8 splitter 4K", "accessory", "splitter", "HSP8", "HDMI 1×8 splitter"),

  // HDMI matrices, presentation switchers
  item("kramer-vs44h2", "Kramer", "VS-44H2", "accessory", "splitter", "V44", "HDMI 4×4 matrix"),
  item("kramer-vs88h2", "Kramer", "VS-88H2", "accessory", "splitter", "V88", "HDMI 8×8 matrix"),
  item("extron-dxp44", "Extron", "DXP 44 HD 4K PLUS", "accessory", "splitter", "DXP", "HDMI 4×4 matrix"),
  item("extron-in1608", "Extron", "IN1608 xi", "accessory", "splitter", "IN16", "presentation switcher"),
  item("aten-vm0404", "ATEN", "VM0404HB", "accessory", "splitter", "V44A", "HDMI 4×4 matrix"),
  item("aten-vm0808", "ATEN", "VM0808HB", "accessory", "splitter", "V88A", "HDMI 8×8 matrix"),
  item("crestron-dmmd88", "Crestron", "DM-MD8X8", "accessory", "splitter", "DM88", "DigitalMedia 8×8"),
  item("atlona-ome", "Atlona", "AT-OME-SW32", "accessory", "splitter", "OME", "3×2 HDMI switcher"),
  item("atlona-hdrh2h", "Atlona", "AT-HDR-H2H-88M", "accessory", "splitter", "H88", "HDMI 8×8 matrix"),
  item("kd-msw4x4", "Key Digital", "KD-MSW4x4", "accessory", "splitter", "MS44", "HDMI 4×4 matrix"),
  item("wyre-mx0404", "WyreStorm", "MX-0404-H2", "accessory", "splitter", "MX44", "HDMI 4×4 matrix"),
  item("lightware-mx28", "Lightware", "MX2-8x8-HDMI20", "accessory", "splitter", "MX28", "HDMI 8×8 matrix"),
  item("gefen-g441", "Gefen", "GTB-HD4K2K-441", "accessory", "splitter", "G441", "4K HDMI 4×1 switcher"),
  item("roland-v1hd", "Roland", "V-1HD", "accessory", "splitter", "V1HD", "HDMI video switcher"),
  item("roland-v8hd", "Roland", "V-8HD", "accessory", "splitter", "V8HD", "HDMI video switcher"),
  item("roland-xs62s", "Roland", "XS-62S", "accessory", "splitter", "XS62", "AV presentation switcher"),
  item("bmd-atemmini", "Blackmagic", "ATEM Mini", "accessory", "splitter", "AMIN", "HDMI live switcher"),
  item("bmd-atem", "Blackmagic", "ATEM Mini Extreme ISO", "accessory", "splitter", "ATEM", "live switcher"),
  item("bmd-atemsdi", "Blackmagic", "ATEM SDI", "accessory", "splitter", "ASDI", "SDI live switcher"),
  item("bmd-atem1me", "Blackmagic", "ATEM 1 M/E Constellation", "accessory", "splitter", "1ME", "4K switcher"),
  item("bmd-uhdstudio", "Blackmagic", "ATEM Television Studio HD8", "accessory", "splitter", "ATS", "live production"),
  item("newtek-tc", "NewTek", "TriCaster Mini 4K", "accessory", "splitter", "TC", "live production"),

  // HDMI / HDBaseT extenders
  item("extron-dtp230", "Extron", "DTP HDMI 4K 230", "accessory", "splitter", "DTP", "HDMI HDBaseT extender"),
  item("extron-dtp330", "Extron", "DTP HDMI 4K 330", "accessory", "splitter", "DTP3", "HDMI 100 m extender"),
  item("kramer-tp580", "Kramer", "TP-580T", "accessory", "splitter", "TP580", "HDMI HDBaseT TX"),
  item("kramer-tp580r", "Kramer", "TP-580R", "accessory", "splitter", "TP58R", "HDMI HDBaseT RX"),
  item("atlona-hdrex70", "Atlona", "AT-HDR-EX-70-2PS", "accessory", "splitter", "EX70", "HDMI 70 m extender"),
  item("crestron-hdtx101", "Crestron", "HD-TX-101-C-E", "accessory", "splitter", "TX101", "DM Lite HDMI TX"),
  item("crestron-hdrx101", "Crestron", "HD-RX-101-C-E", "accessory", "splitter", "RX101", "DM Lite HDMI RX"),
  item("wyre-ex70", "WyreStorm", "EX-70-H2", "accessory", "splitter", "EX70W", "HDMI 70 m extender"),
  item("hall-uhbx", "Hall Research", "UHBX-3S-S", "accessory", "splitter", "UHBX", "HDMI HDBaseT extender"),
  item("kanex-hdbt70", "KanexPro", "EXT-HDBT70M", "accessory", "splitter", "K70", "HDMI 70 m extender"),
  item("gefen-cat5elr", "Gefen", "EXT-UHD-CAT5-ELRPOL", "accessory", "splitter", "GELR", "4K HDMI over Cat5"),
  item("mono-hdbt", "Monoprice", "Blackbird HDBaseT 70m", "accessory", "splitter", "BB70", "HDMI HDBaseT extender"),
  item("binary-hdbt", "Binary", "B-520-EXT-330-2", "accessory", "splitter", "B330", "HDMI HDBaseT extender"),
  item("kd-cathd", "Key Digital", "KD-CATHD1000", "accessory", "splitter", "CATH", "HDMI over Cat extender"),

  // SDI DA, converters, scalers
  item("bmd-sdi-dist", "Blackmagic", "Mini Converter SDI Distribution 4K", "accessory", "splitter", "SDID", "SDI 1×4 DA"),
  item("bmd-sdihdmi", "Blackmagic", "Mini Converter SDI to HDMI 4K", "accessory", "splitter", "S2H", "SDI to HDMI converter"),
  item("bmd-hdmisdi", "Blackmagic", "Mini Converter HDMI to SDI 4K", "accessory", "splitter", "H2S", "HDMI to SDI converter"),
  item("bmd-teranex", "Blackmagic", "Teranex Mini SDI to HDMI 12G", "accessory", "splitter", "TNX", "12G-SDI to HDMI"),
  item("aja-hd10da", "AJA", "HD10DA", "accessory", "splitter", "HD10", "SDI 1×6 DA"),
  item("aja-kumo1616", "AJA", "KUMO 1616", "accessory", "splitter", "KUMO", "SDI 16×16 router"),
  item("aja-ha54k", "AJA", "HA5-4K", "accessory", "splitter", "HA5", "HDMI to SDI 4K"),
  item("aja-hi54k", "AJA", "Hi5-4K", "accessory", "splitter", "HI5", "SDI to HDMI 4K"),
  item("aja-ha5plus", "AJA", "HA5-Plus", "accessory", "splitter", "HA5P", "HDMI to SDI"),
  item("decimator-mdhx", "Decimator", "MD-HX", "accessory", "splitter", "MDHX", "HDMI/SDI cross converter"),
  item("decimator-dmon", "Decimator", "DMON-16S", "accessory", "splitter", "DM16", "16-ch SDI monitor"),
  item("roland-vc1hs", "Roland", "VC-1-HS", "accessory", "splitter", "VC1H", "HDMI to SDI converter"),
  item("roland-vc1sh", "Roland", "VC-1-SH", "accessory", "splitter", "VC1S", "SDI to HDMI converter"),
  item("kramer-vm4hdxl", "Kramer", "VM-4HDxl", "accessory", "splitter", "V4HD", "3G-SDI 1×4 DA"),
  item("extron-da4sdi", "Extron", "DA4 HD-SDI", "accessory", "splitter", "DAS", "HD-SDI 1×4 DA"),
  item("kramer-fc32", "Kramer", "FC-32", "accessory", "splitter", "FC32", "HDMI to SDI converter"),
  item("extron-dsc3g", "Extron", "DSC 3G-HD A", "accessory", "splitter", "DSC", "3G-SDI to HDMI scaler"),
  item("extron-dschd3g", "Extron", "DSC HD-3G A", "accessory", "splitter", "DSC2", "HDMI to 3G-SDI scaler"),
  item("kramer-vp427", "Kramer", "VP-427", "accessory", "splitter", "VP427", "HDMI presentation scaler"),
  item("crestron-hdscaler", "Crestron", "HD-SCALER-HD-E", "accessory", "splitter", "SCAL", "HDMI scaler"),
  item("aten-vc880", "ATEN", "VC880", "accessory", "splitter", "VC880", "HDMI audio extractor"),
  item("tvone-corio", "tvONE", "CORIOview", "accessory", "splitter", "CORIO", "multiview processor"),
  item("magewell-usb4k", "Magewell", "USB Capture HDMI 4K Plus", "accessory", "splitter", "MW4K", "HDMI capture"),
  item("elgato-4kx", "Elgato", "4K X", "accessory", "splitter", "E4KX", "HDMI capture"),

  // DI boxes
  item("di-radial", "Radial", "JDI", "accessory", "dibox", "JDI", "passive DI box"),
  item("di-j48", "Radial", "J48", "accessory", "dibox", "J48", "active DI box"),
  item("di-prodi", "Radial", "ProDI", "accessory", "dibox", "PDI", "passive DI box"),
  item("di-jdiduplex", "Radial", "JDI Duplex", "accessory", "dibox", "JDID", "stereo passive DI box"),
  item("di-prod2", "Radial", "ProD2", "accessory", "dibox", "PD2", "stereo passive DI box"),
  item("di-pro48", "Radial", "Pro48", "accessory", "dibox", "P48", "active DI box"),
  item("di-pzdi", "Radial", "PZ-DI", "accessory", "dibox", "PZDI", "piezo DI box"),
  item("di-usbpro", "Radial", "USB-Pro", "accessory", "dibox", "USBD", "USB stereo DI box"),
  item("di-sb1", "Radial", "StageBug SB-1", "accessory", "dibox", "SB1", "compact acoustic DI"),
  item("di-sb2", "Radial", "StageBug SB-2", "accessory", "dibox", "SB2", "compact passive DI"),
  item("di-sb5", "Radial", "StageBug SB-5", "accessory", "dibox", "SB5", "laptop stereo DI"),
  item("di-proav1", "Radial", "ProAV1", "accessory", "dibox", "PAV1", "multimedia DI box"),
  item("di-proav2", "Radial", "ProAV2", "accessory", "dibox", "PAV2", "stereo multimedia DI"),
  item("di-btpro", "Radial", "BT-Pro V2", "accessory", "dibox", "BTPR", "Bluetooth DI box"),
  item("di-trimtwo", "Radial", "Trim-Two", "accessory", "dibox", "TRIM", "stereo DI + trim"),
  item("di-jpc", "Radial", "JPC", "accessory", "dibox", "JPC", "computer DI box"),
  item("di-prod8", "Radial", "ProD8", "accessory", "dibox", "PD8", "8-ch rack DI"),
  item("di-bss", "BSS", "AR-133", "accessory", "dibox", "AR", "active DI box"),
  item("di-whirl", "Whirlwind", "IMP 2", "accessory", "dibox", "IMP", "passive DI box"),
  item("di-whirl-pcdi", "Whirlwind", "pcDI", "accessory", "dibox", "PCDI", "computer stereo DI"),
  item("di-whirl-dir", "Whirlwind", "Director", "accessory", "dibox", "DIR", "active DI box"),
  item("di-whirl-edb1", "Whirlwind", "EDB1", "accessory", "dibox", "EDB1", "passive DI box"),
  item("di-country", "Countryman", "Type 85", "accessory", "dibox", "T85", "active DI box"),
  item("di-type10", "Countryman", "Type 10", "accessory", "dibox", "T10", "active DI box"),
  item("di-type85s", "Countryman", "Type 85S", "accessory", "dibox", "T85S", "stereo active DI"),
  item("di-behr-di100", "Behringer", "DI100 Ultra-DI", "accessory", "dibox", "DI1", "active DI box"),
  item("di-behr-di4000", "Behringer", "DI4000", "accessory", "dibox", "DI4K", "4-ch rack DI"),
  item("di-behr-di20", "Behringer", "DI20", "accessory", "dibox", "DI20", "passive stereo DI"),
  item("di-art-pdb", "ART", "PDB", "accessory", "dibox", "PDB", "passive DI box"),
  item("di-art-dualz", "ART", "DualZDirect", "accessory", "dibox", "DZD", "passive stereo DI"),
  item("di-palmer-pan01", "Palmer", "PAN 01", "accessory", "dibox", "PAN1", "passive DI box"),
  item("di-palmer-pan04", "Palmer", "PAN 04", "accessory", "dibox", "PAN4", "passive stereo DI"),
  item("di-rndi", "Rupert Neve Designs", "RNDI", "accessory", "dibox", "RNDI", "active DI box"),
  item("di-rndis", "Rupert Neve Designs", "RNDI-S", "accessory", "dibox", "RNDS", "stereo active DI"),
  item("di-rndi8", "Rupert Neve Designs", "RNDI-8", "accessory", "dibox", "RND8", "8-ch rack DI"),
  item("di-klark-dn100", "Klark Teknik", "DN100", "accessory", "dibox", "DN100", "active DI box"),
  item("di-klark-di10a", "Klark Teknik", "DI 10A", "accessory", "dibox", "DI10", "active DI box"),
  item("di-rapco-db1", "RapcoHorizon", "DB-1", "accessory", "dibox", "DB1", "passive DI box"),
  item("di-proco-cb1", "Pro Co", "CB-1", "accessory", "dibox", "CB1", "passive DI box"),
  item("di-samson-mda1", "Samson", "S-Max MDA1", "accessory", "dibox", "MDA1", "active DI box"),
  item("di-rolls-db25", "Rolls", "DB25", "accessory", "dibox", "DB25", "passive DI box"),
  item("di-littlelabs", "Little Labs", "Redeye 3D Phantom", "accessory", "dibox", "REDE", "DI / reamp"),
  item("generic-dibox", "Generic", "Passive DI box", "accessory", "dibox", "DI", "passive DI box"),

  // Isolators, mic splitters, hum eliminators
  item("di-twiniso", "Radial", "Twin-Iso", "accessory", "dibox", "TISO", "line isolator"),
  item("di-icecube", "Radial", "IceCube IC-1", "accessory", "dibox", "ICE", "hum eliminator"),
  item("di-proms2", "Radial", "ProMS2", "accessory", "dibox", "MS2", "mic splitter 1×2"),
  item("di-js3", "Radial", "JS3", "accessory", "dibox", "JS3", "mic splitter 1×3"),
  item("di-ox8", "Radial", "OX8-r", "accessory", "dibox", "OX8", "8-ch mic splitter"),
  item("whirl-ms12", "Whirlwind", "MultiSplitter MS-12", "accessory", "dibox", "MS12", "mic splitter"),
  item("art-s8", "ART", "S8", "accessory", "dibox", "S8", "8-ch mic splitter"),
  item("jensen-pi2xx", "Jensen", "ISO-MAX PI-2XX", "accessory", "dibox", "JISO", "2-ch isolator"),
  item("ebtech-he2", "Ebtech", "Hum Eliminator HE-2", "accessory", "dibox", "HE2", "2-ch hum eliminator"),
  item("ebtech-humx", "Ebtech", "Hum X", "accessory", "dibox", "HUMX", "ground loop interrupter"),
  item("whirl-iso8", "Whirlwind", "ISO-8", "accessory", "dibox", "ISO8", "8-ch isolator"),
  item("sescom-il19", "Sescom", "IL-19", "accessory", "dibox", "IL19", "isolation transformer"),
  item("neutrik-na2f", "Neutrik", "NA2F-D2B-TX", "accessory", "dibox", "NA2F", "XLR to RCA transformer"),

  // Wall plates, cubbies, floor boxes
  item("extron-cubby202", "Extron", "Cable Cubby 202", "accessory", "jbox", "CC202", "table cable cubby"),
  item("extron-hsa200", "Extron", "HSA 200", "accessory", "jbox", "HSA", "hideaway cable well"),
  item("extron-wpd110", "Extron", "WPD 110 AAP", "accessory", "datajack", "WPD", "HDMI wall plate"),
  item("extron-retractor", "Extron", "Cable Retractor", "accessory", "jbox", "RETR", "cable retractor"),
  item("crestron-ft2700", "Crestron", "FT2-700", "accessory", "jbox", "FT2", "flip-top cable well"),
  item("kramer-wph", "Kramer", "WP-20", "accessory", "datajack", "WP20", "HDMI wall plate"),
  item("kramer-tbus", "Kramer", "TBUS-10xl", "accessory", "jbox", "TBUS", "table connectivity"),
  item("atlona-wp", "Atlona", "AT-HDVS-210U-TX-WP", "accessory", "datajack", "HDVS", "USB-C/HDMI wall TX"),
  item("fsr-t3", "FSR", "T3-AC2", "accessory", "jbox", "T3", "table box"),
  item("legrand-evo", "Legrand", "Wiremold Evolution", "accessory", "jbox", "EVO", "floor box"),
  item("c2g-hdmiwp", "C2G", "HDMI Wall Plate", "accessory", "datajack", "C2GW", "HDMI pass-through"),
  item("liberty-wp", "Liberty", "Decora HDMI/USB", "accessory", "datajack", "LWP", "AV wall plate"),
  item("ma-ucp", "Middle Atlantic", "UCP", "accessory", "jbox", "UCP", "universal connector panel"),

  // Patchbays, snakes
  item("neutrik-nys", "Neutrik", "NYS-SPP-L1", "accessory", "jbox", "NYS", "1/4 in patchbay"),
  item("bittree-2x48", "Bittree", "2x48 TT", "accessory", "jbox", "BT48", "TT patchbay"),
  item("switchcraft-9625", "Switchcraft", "9625", "accessory", "jbox", "SW96", "1/4 in patchbay"),
  item("samson-spatch", "Samson", "S-Patch Plus", "accessory", "jbox", "SPCH", "48-pt patchbay"),
  item("art-p16", "ART", "P16", "accessory", "jbox", "P16", "1/4 in patchbay"),
  item("whirl-pb12", "Whirlwind", "PB12", "accessory", "jbox", "PB12", "12-pt patchbay"),
  item("whirl-medusa", "Whirlwind", "Medusa", "accessory", "stagebox", "MED", "multicore snake"),
  item("rapco-ms16", "RapcoHorizon", "MS-16x4", "accessory", "stagebox", "MS16", "16-ch analog snake"),
  item("hosa-sh16", "Hosa", "SH-16x4", "accessory", "stagebox", "SH16", "16-ch snake"),
  item("canare-starquad16", "Canare", "16-ch starquad snake", "accessory", "stagebox", "C16", "starquad multicore"),

  // Antenna distribution
  item("shure-ua844", "Shure", "UA844+SWB", "accessory", "shure", "UA844", "antenna distro"),
  item("shure-ua874", "Shure", "UA874", "accessory", "shure", "UA874", "active directional antenna"),
  item("senn-asa214", "Sennheiser", "ASA 214", "accessory", "shure", "ASA", "antenna splitter"),
  item("rfv-distro4", "RF Venue", "DISTRO4", "accessory", "shure", "D4", "4-ch antenna distro"),
  item("rfv-divfin", "RF Venue", "Diversity Fin", "accessory", "shure", "DFIN", "diversity antenna"),

  // Headphone amps, phantom
  item("behr-ha8000", "Behringer", "HA8000", "accessory", "dibox", "HA8K", "8-ch headphone amp"),
  item("art-headamp6", "ART", "HeadAmp 6 Pro", "accessory", "dibox", "HA6", "6-ch headphone amp"),
  item("presonus-hp60", "PreSonus", "HP60", "accessory", "dibox", "HP60", "6-ch headphone amp"),
  item("art-phantom2", "ART", "Phantom II Pro", "accessory", "dibox", "PH2", "dual phantom supply"),
  item("rolls-pb23", "Rolls", "PB23", "accessory", "dibox", "PB23", "phantom power supply"),

  // Wireless present, USB extenders, intercom, media players
  item("kramer-via-c2", "Kramer", "VIA Connect 2", "accessory", "splitter", "VIA", "wireless present"),
  item("kramer-viago2", "Kramer", "VIA Go²", "accessory", "splitter", "VIAG", "wireless present"),
  item("mersive-pod", "Mersive", "Solstice Pod", "accessory", "splitter", "SOL", "wireless present"),
  item("extron-sharelink", "Extron", "ShareLink 250 W", "accessory", "splitter", "SL250", "wireless present"),
  item("crestron-am300", "Crestron", "AM-3000-WF", "accessory", "splitter", "AM3K", "AirMedia present"),
  item("icron-ranger", "Icron", "USB Ranger 2304", "accessory", "splitter", "USBX", "USB 2.0 extender"),
  item("extron-usbext", "Extron", "USB Extender Plus", "accessory", "splitter", "USBE", "USB extender"),
  item("aten-ueh", "ATEN", "UEH4102", "accessory", "splitter", "UEH", "USB over Cat extender"),
  item("clearcom-fs2", "Clear-Com", "FreeSpeak II", "accessory", "zoomctrl", "FS2", "wireless intercom"),
  item("clearcom-helix", "Clear-Com", "HelixNet", "accessory", "zoomctrl", "HLX", "digital partyline"),
  item("rts-bp325", "RTS", "BP-325", "accessory", "zoomctrl", "BP325", "beltpack intercom"),
  item("brightsign-xt", "BrightSign", "XT1144", "accessory", "zoompc", "XT11", "4K media player"),
  item("brightsign-hd5", "BrightSign", "HD5", "accessory", "zoompc", "HD5", "HD media player"),
  item("spinetix-hmp400", "SpinetiX", "HMP400", "accessory", "zoompc", "HMP", "4K media player"),

  // Other
  item("intel-nuc", "Intel", "NUC 13 Pro", "other", "zoompc", "NUC", "Zoom Room host"),
  item("dell-micro", "Dell", "OptiPlex Micro", "other", "zoompc", "OPT", "Zoom Room host"),
  item("hp-mini", "HP", "Elite Mini 800", "other", "zoompc", "ELITE", "Zoom Room host"),
  item("barco-cx30", "Barco", "ClickShare CX-30", "conference", "splitter", "CX30", "wireless share"),
];

export const CATEGORY_META: Record<CatalogCategory, { label: string }> = {
  mixer: { label: "Mixers" },
  stagebox: { label: "Stage boxes" },
  amplifier: { label: "Amplifiers" },
  speaker: { label: "Speakers" },
  microphone: { label: "Microphones" },
  wireless: { label: "Wireless" },
  camera: { label: "Cameras" },
  display: { label: "Displays" },
  conference: { label: "Conferencing" },
  network: { label: "Network" },
  dsp: { label: "DSP" },
  control: { label: "Control" },
  rack: { label: "Racks" },
  power: { label: "Power" },
  cable: { label: "Cables" },
  stage: { label: "Stage" },
  accessory: { label: "Accessories" },
  other: { label: "Other" },
};

export const CATEGORY_ORDER: CatalogCategory[] = [
  "mixer",
  "stagebox",
  "amplifier",
  "speaker",
  "microphone",
  "wireless",
  "camera",
  "display",
  "conference",
  "network",
  "dsp",
  "control",
  "rack",
  "power",
  "cable",
  "stage",
  "accessory",
  "other",
];

export const CATEGORY_DEFAULTS: Record<CatalogCategory, { kind?: DeviceKind; cable?: CableKind }> = {
  mixer: { kind: "mixer" },
  stagebox: { kind: "stagebox" },
  amplifier: { kind: "amp" },
  speaker: { kind: "speaker" },
  microphone: { kind: "mic" },
  wireless: { kind: "shure" },
  camera: { kind: "camera" },
  display: { kind: "display" },
  conference: { kind: "neatbar" },
  network: { kind: "netswitch" },
  dsp: { kind: "dsp" },
  control: { kind: "zoomctrl" },
  rack: { kind: "rack" },
  power: { kind: "pdu" },
  cable: { cable: "xlr" },
  stage: { kind: "keys" },
  accessory: { kind: "splitter" },
  other: { kind: "jbox" },
};

const KIND_ALIASES: Partial<Record<DeviceKind, string>> = {
  splitter: "splitter distribution da matrix extender converter scaler switcher accessory",
  dibox: "di box dibox direct box isolation transformer hum eliminator mic splitter accessory",
};

export function searchCatalog(
  items: CatalogItem[],
  query: string,
  category?: CatalogCategory | "all",
  brand?: string | "all",
): CatalogItem[] {
  const q = query.trim().toLowerCase();
  const parts = q.split(/\s+/).filter(Boolean);
  const out = items.filter((it) => {
    if (category && category !== "all" && it.category !== category) return false;
    if (brand && brand !== "all" && it.brand !== brand) return false;
    if (!q) return true;
    const kindLabel = it.kind ? DEVICE_META[it.kind].label : "";
    const aliases = it.kind ? KIND_ALIASES[it.kind] ?? "" : "";
    const hay =
      `${it.brand} ${it.model} ${it.short} ${it.spec ?? ""} ${it.category} ${CATEGORY_META[it.category].label} ${kindLabel} ${aliases}`.toLowerCase();
    return parts.every((part) => hay.includes(part));
  });
  const score = (it: CatalogItem) => {
    if (!q) return 0;
    const spec = (it.spec ?? "").toLowerCase();
    const model = `${it.brand} ${it.model}`.toLowerCase();
    if (spec.includes(q) || model.includes(q)) return 0;
    if (parts.every((p) => spec.includes(p) || model.includes(p))) return 1;
    return 2;
  };
  out.sort((a, b) => score(a) - score(b) || a.brand.localeCompare(b.brand) || a.model.localeCompare(b.model));
  return out;
}

export function catalogBrands(items: CatalogItem[]): string[] {
  return [...new Set(items.map((it) => it.brand))].sort((a, b) => a.localeCompare(b));
}

export function findCatalogItem(items: CatalogItem[], id: string | undefined): CatalogItem | undefined {
  if (!id) return undefined;
  return items.find((it) => it.id === id);
}

export const STOCK_STATS = {
  models: STOCK_CATALOG.length,
  brands: catalogBrands(STOCK_CATALOG).length,
};
